## Qu'est-ce que le [web scraping](https://librarycarpentry.org/lc-webscraping/01-introduction/index.html) ?

<br>

- Le [web scraping](https://fr.wikipedia.org/wiki/Web_scraping) désigne un ensemble de techniques d'__extraction de contenu__ sur des sites internet.

. . .

- Le terme fait généralement référence à l'usage de [bots](https://en.wikipedia.org/wiki/Internet_bot) pour collecter ces contenus automatiquement.


## Exemples introductifs

<br>

- On souhaite accéder à la [liste des présidents des États-Unis](https://fr.wikipedia.org/wiki/Liste_des_pr%C3%A9sidents_des_%C3%89tats-Unis) et réunir les dates de mandat dans un `Excel`.

. . .

- On souhaite télécharger le [classement QS 2023 des universités](https://www.universityrankings.ch/results/QS/2023) et filtrer les universités italiennes.

. . .


- On souhaite accéder à un [répertoire d'expressions idiomatiques](https://fr.wiktionary.org/wiki/Annexe:Expressions_en_fran%C3%A7ais) et trouver toutes celles contenant le mot "nez".


## `Web scraping`, `web crawling`, `screen scraping`, quelles différences ? {.smaller}

<br>

- Le [web scraping](https://en.wikipedia.org/wiki/Web_scraping) se réfère à l'extraction des données d'une ou plusieurs pages web.

. . .

- Le [web crawling](https://en.wikipedia.org/wiki/Web_crawler), ou [spidering]{.blue2} correspond à la recherche (ou la navigation parmi) de nouveaux URLs sur Internet ou sur un site spécifique.

. . .

- Quant au [screen scraping](https://en.wikipedia.org/wiki/Data_scraping#Screen_scraping), proche du web scraping, il consiste plutôt à extraire le contenu visuel d'un site apparaissant à l'écran, comme des images.

. . .

::: {.callout-note}
`Web scraping` et `web crawling` peuvent aller ensemble : 

- On utile d'abord un crawler pour récupérer tous les urls d'un site ...
- ... Puis on scrape chacune des pages les unes après les autres
:::

## Cas d'usage pratiques

#### Études de marché et intelligence économique

- Faire un suivi des prix sur des site de ventes (possiblement concurrents) en les scrapant régulièrement
    + On peut alors parler de [price scraping](https://www.minderest.com/fr/blog/qu-est-ce-que-price-scraping)
 
. . . 

- Glaner des informations sur les sites d'entreprises concurrentes

::: {.callout-tip}
## Exemple

Dans les répertoires d'expressions idiomatiques, il est facile de "dérober" les contenus les uns des autres ([Expressio](https://www.expressio.fr/toutes-les-expressions), [Expressions Françaises](https://www.expressions-francaises.fr/), [L'internaute](https://www.linternaute.fr/expression/)...)
:::


## Cas d'usage pratiques

#### Analyses de sentiment et génération de _leads_

<br>

- Récupérer les commentaires d'un produit ou d'une entreprise sur un site tiers afin d'analyser les retours obtenus et faire du _sentiment analysis_
    + Un [papier de recherche](https://doi.org/10.1007/978-3-030-16660-1_66) sur le sujet

. . .

- Obtenir une liste de clients potentiels ou répondant à des critères spécifiques 
    + À partir de sites comme les [Pages Jaunes](https://www.pagesjaunes.fr/pagesblanches) ou [Google Maps](https://www.google.com/business/) pour les entreprises


## Cas d'usage pratiques

#### Obtenir des données pour alimenter des modèles de ML

- Regrouper divers indicateurs et séries temporelles via les [Google Trends](https://trends.google.fr/trends/?geo=FR) pour améliorer les performances de modèles de prédiction
    + En phase expérimentale à l'INSEE, par exemple pour des problématiques de [nowcasting](https://statistics-awards.eu/competitions/3)

. . .

- Surveiller les valeurs de stocks boursiers et mouvements de marché sur [Yahoo Finance](https://fr.finance.yahoo.com/) et les inclure dans des modèles
    + En l'occurrence, `Yahoo Finance` offre aussi une [API](https://algotrading101.com/learn/yahoo-finance-api-guide/) pour l'extraction de données


## Cas d'usage pratiques {.smaller}

#### Dans des domaines spécifiques

<br>

- Dans le domaine immobilier, de nombreuses agences utilisent le scraping pour alimenter leur propre base de biens à vendre ou à louer.
    + On peut aussi trouver de nombreux agrégateurs d'annonces en ligne.

. . .

- Dans le domaine aérien, nombreux sont les comparateurs en ligne qui ont recours au scraping pour présenter des offres de trajets issues de plusieurs compagnies.
    + Ex : [kiwi.com](https://www.kiwi.com/fr/), [lastminute.com](https://www.fr.lastminute.com/)...
    + Ce n'est d'ailleurs pas le cas que dans le domaine du transport (ex: hébergement touristique).

. . .

- Dans le domaine des paris sportifs, il est courant de scraper les sites de statistiques sportives afin d'adapter l'offre des paris.


## Cas d'usage pratiques

#### Dans le domaine de la recherche

<br>

- Pour des chercheurs, le webscraping peut représenter une importance source de données, et ce dans des domaines très variés.

    + Un exemple [ici](https://www.nature.com/articles/s41597-022-01369-4) avec une équipe ayant scrapé [Wikipedia](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal) et [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page) afin d'établir une base de données de tous les individus ayant leur propre page, pour ensuite établir des statistiques par période, par domaine ou par sexe. 


## Cas d'usage pour un INS

<br>

- Scraper divers sites de ventes afin d'obtenir des données de prix pour le __calcul de l'indice des prix à la consommation__ (`IPC`)

. . .

- Compléter des données de statistiques d'entreprises avec des informations disponibles en ligne

. . .

- Minimiser les fardeaux de réponse lors des enquêtes en favorisant le scraping
