## Comprendre la nature d'une page web {.smaller}

- Un site Internet est constitué de diverses __pages Web__.
   + Celles-ci sont le produit de fichiers appelés __codes source__ des pages.

. . .

- Les 3 langages principaux pour les coder sont :
    + [HTML](https://developer.mozilla.org/fr/docs/Web/HTML) : pour composer la structure des pages via un système de balises
    + [CSS](https://developer.mozilla.org/fr/docs/Web/CSS) : des feuilles de style pour décrire la présentation de pages `HTML`
    + [JavaScript](https://developer.mozilla.org/fr/docs/Web/JavaScript) : pour tout ce qui est relatif à l'interactivité d'un site (ex : boutons)

. . .

::: {.callout-tip}
## Pour en apprendre plus

Deux ressources-clés :

- [W3C](https://www.w3.org/) : World Wide Web Consortium
- [MDN Web Docs](https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web) : Mozilla Developer Network
:::

## Inspecter une page web

<br>

- Il est possible d'afficher le __code source__ des pages Web, au sein duquel les scrapeurs doivent naviguer.

<br>

- `Clic droit` sur la page puis
    + _"Inspecter l'élément"_ pour observer un endroit spécifique de la page
    + _"Afficher le code source de la page"_ pour afficher le code de toute la page


## Hiérarchisation d'une page web {.smaller}

#### Les balises `HTML`

<br>

- Sur une page web, vous trouverez à coup sûr des éléments comme ``<head>``, ``<title>``, etc. Il  s'agit des codes qui vous permettent de structurer le contenu d'une page `HTML` et qui s'appellent des **balises**. 
    + Par exemple, les balises ``<p>``, ``<h1>``, ``<h2>``, ``<h3>``, ``<strong>`` ou ``<em>``.

. . .

- Le symbole ``< >`` est une balise : il sert à indiquer le début d'une partie. Le symbole ``</ >`` indique la fin de cette partie.

. . .

- La plupart des balises vont par paires, avec une *balise ouvrante* et une *balise fermante* (par exemple ``<p>`` et ``</p>``).


## Exemple : les balises de tableau

<br>

| Balise      | Description                        |
|-------------|------------------------------------|
| `<table>`   | Tableau                            |
| `<caption>` | Titre du tableau                   |
| `<tr>`      | Ligne de tableau                   |
| `<th>`      | Cellule d'en-tête                  |
| `<td>`      | Cellule                            |
| `<thead>`   | Section de l'en-tête du tableau    |
| `<tbody>`   | Section du corps du tableau        |
| `<tfoot>`   | Section du pied du tableau         |


## Un exemple : un tableau `HTML`

<br>

```{html}
<table>
<caption> Le Titre de mon tableau </caption>
   <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Profession</th>
   </tr>
   <tr>
      <td>Mike </td>
      <td>Stuntman</td>
      <td>Cascadeur</td>
   </tr>
   <tr>
      <td>Mister</td>
      <td>Pink</td>
      <td>Gangster</td>
   </tr>
</table>
```

## Un exemple : un tableau `HTML`

<br>

<table>
<caption> Le Titre de mon tableau </caption>

   <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Profession</th>
   </tr>
   <tr>
      <td>Mike </td>
      <td>Stuntman</td>
      <td>Cascadeur</td>
   </tr>
   <tr>
      <td>Mister</td>
      <td>Pink</td>
      <td>Gangster</td>
   </tr>
</table>


## Scraping d'une page web

<br>

- Le web scraping consiste à naviguer parmi ces balises `HTML` pour extraire le contenu désiré (textes, tableaux, images, ...).

. . .

- Il est aussi possible de récupérer d'autres url sur une page pour s'y rendre et les scraper ensuite.

. . .

- Dans certains cas plus complexes, lire le contenu `HTML` ne suffit pas,
   + Par exemple s'il faut cliquer sur des boutons pour faire apparaître le contenu désiré.


## [XPath](https://librarycarpentry.org/lc-webscraping/02-xpath/index.html)

<br>

- Une page web peut aussi se présenter sous le format `XML`, proche du `HTML`.

. . .

- Afin de justement naviguer dans une page `HTML` ou `XML`, on fait appel à un langage d'expressions appelé `XPath`.
   + Ce sont des expressions `XPath` qui seront utilisées en appel des fonctions.
   + `XPath` permet ainsi de se déplacer de noeud en noeud dans la structure arborescente d'une page.
