## Le web scraping, est-ce légal ?

<br>

- Le web scraping en lui-même n'est pas une pratique illégale ...
    - ... Mais l'utilisation faite des données scrapées peut être soumise à réglementation.
    - Ces règles dépendent alors du pays dans lequel on se trouve ainsi que des données scrapées. 

. . .

::: {.callout-important}
## Attention

Diffuser ou commercialiser des données scrapées ou un quelconque travail réutilisant ces données n'est pas sans conséquence.
:::


## Une frontière floue

- Les législations spécifiques au web scraping sont peu nombreuses et différentes d'un pays à l'autre.

. . .

- En revanche, la réutilisation des données est encadrée.
    + Par exemple par le code de la propriété intellectuelle ou par le `RGPD`.

. . .

- Les [cas portés en justice](https://devm.io/law-net-culture/data-scraping-cases-165385) ont des dénouements parfois différents les uns des autres, notamment d'un pays à l'autre, montrant bien qu'il s'agit là d'une zone parfois grise.


## Une pratique pourtant très répandue

<br>

- Les cas d'usage, y compris dans de grandes entreprises, sont très nombreux.

. . .

- Les articles discutant de web scraping et de leur légalité sont tout aussi proliférants, mais pas toujours d'accord les uns avec les autres.
    - Quelques ressources : [Imperva](https://www.imperva.com/blog/is-web-scraping-illegal/), [Islean Consulting](https://islean-consulting.fr/fr/transformation-digitale/scraping-pages-web-legal/), [TechCrunch](https://techcrunch.com/2022/04/18/web-scraping-legal-court/)...


## Les principales réglementations autour du web scraping {.smaller}

#### En France

- [L'article L.\ 342-1 du code de la propriété intellectuelle](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006279247)

- [L'article L.\ 342-2 du code de la propriété intellectuelle](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006279250)

. . .

- L'[article 323-3 du code pénal](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030939448) : _"Le fait [...] d'extraire, de détenir, de reproduire [...] frauduleusement les données qu'il [le site] contient est puni de cinq ans d'emprisonnement et de 150 000 € d'amende"_

. . .

- En termes de droit de la concurrence, on pourra aussi parler de concurrence déloyale avec l'[article L.\ 121-1 du code de la consommation](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032227301/)

. . .

- Il serait même possible de parler de parasitisme et invoquer l’[article 1240 du code civil](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032041571)

. . .

- La `CNIL` a également publié en 2020 un ensemble de [nouvelles directives](https://www.cnil.fr/fr/la-reutilisation-des-donnees-publiquement-accessibles-en-ligne-des-fins-de-demarchage-commercial), limitant l'usage de données personnelles, même si publiques, à usage commercial


## Les principales réglementations autour du web scraping {.smaller}

#### En Europe (1/2)

- La [Directive 96/9/CE](https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX:31996L0009:fr:HTML) du Parlement Européen et du conseil
    + Elle introduit notamment le droit [sui generis](https://fr.wikipedia.org/wiki/Sui_generis), protégeant les bases de données ayant nécessité un _"investissement substantiel"_

    + >  Le fabricant d’une base de données [a] le droit d’interdire l’extraction et/ou la réutilisation de la totalité ou d’une partie substantielle, évaluée de façon qualitative ou quantitative, du contenu de celle-ci, lorsque l’obtention, la vérification ou la présentation de ce contenu attestent un investissement substantiel du point de vue qualitatif ou quantitatif

    + > L’extraction et/ou la réutilisation répétées et systématiques de parties non substantielles du contenu de la base de données qui supposeraient des actes contraires à une exploitation normale de cette base, ou qui causeraient un préjudice injustifié aux intérêts légitimes du fabricant de la base, ne sont pas autorisées


## Les principales réglementations autour du web scraping {.smaller}

#### En Europe (2/2)

<br>

- Le [RGPD](https://www.cnil.fr/fr/reglement-europeen-protection-donnees), sur l'utilisation des données à caractère personnel
    + Règlement européen mais d'application extraterritoriale
    + [5 grands principes](https://www.cnil.fr/fr/cnil-direct/question/quels-sont-les-grands-principes-des-regles-de-protection-des-donnees) :
        - Le principe de finalité
        - Le principe de proportionnalité et de pertinence
        - Le principe d'une durée de conservation limitée
        - Le principe de sécurité et de confidentialité
        - Les droits des personnes 

. . .

- Le [Data Governance Act](https://info.haas-avocats.com/droit-digital/data-governance-act-reglement-europeen), prévu pour septembre 2023


## Les principales réglementations autour du web scraping {.smaller}

#### Encore d'autres

<br>

- Les __jurisprudences__ issues des procès d'entreprises liés au web scraping

. . .

- Les mentions légales, conditions d'utilisation et autres consignes des sites concernés
    + D'autant plus engageantes quand accéder au contenu nécessite d'accepter explicitement les conditions du site (par exemple en appuyant sur un bouton)

. . .

- Aux États-Unis, plusieurs textes peuvent s'appliquer, entre autres :
    + Le [California Consumer Privacy Act](https://oag.ca.gov/privacy/ccpa)
    + Le [Computer Fraud and Abuse Act](https://www.nacdl.org/Landing/ComputerFraudandAbuseAct)


## Les sites se protègent aussi eux-mêmes

<br>

- Afin d'éviter la réutilisation de leurs contenus par des concurrents et lutter contre l'espionnage

. . .

- Afin de bloquer les `bots` qui occupent une partie significative du trafic, ralentissant ainsi l'accès au site
    + Un scraping mal fait peut s'assimiler à une [attaque par déni de service](https://fr.wikipedia.org/wiki/Attaque_par_d%C3%A9ni_de_service) (`DoS`)


## Les méthodes mises en place pour se protéger du scraping (1/2) {.smaller}

<br>

- Mettre en place des [__conditions d'utilisation__]{.blue2} contraignantes et instructions explicites pour se protéger d'un point de vue légal

. . .

- Repérer les [__adresses IP suspectes__]{.blue2} et [__bloquer leur accès__]{.blue2} au site, temporairement ou de façon permanente

. . .

- [__Identifier les bots__]{.blue2} et leur afficher un contenu différent des utilisateurs classiques, pour par exemple [__renvoyer de fausses données__]{.blue2}

. . .

- [__Limiter les requêtes ou la bande passante consommée__]{.blue2} par une même source, pouvant ainsi conduire à des collectes partielles ou interrompues


## Les méthodes mises en place pour se protéger du scraping (2/2)

- [__Modifier régulièrement le format `HTML`__]{.blue2} du contenu pour empêcher l'automatisation du scraping par autrui

. . .

- [__Créer des pages [Honeypot](https://fr.wikipedia.org/wiki/Honeypot)__]{.blue2} qu'un humain ne visiterait jamais pour identifier puis bloquer des bots

. . .

- [__Utiliser des CAPTCHAs__]{.blue2} lorsqu'une activité suspecte est repérée

. . .

- [__Nécessiter une identification__]{.blue2} pour accéder au contenu du site


## Les limites du web scraping {.smaller}

- La qualité des données obtenues par scraping n'est pas toujours au rendez-vous.
    + De plus, vérification manuelle à faire pour vérifier qu'un faux contenu n'a pas été renvoyé par le site.

. . .

- Il faut 'lutter' contre les sites qui se défendent contre le scraping, ce qui n'est pas sans effort.
    + Modifications manuelles des codes à faire régulièrement, rendant l'__automatisation très difficile__.
    + Pérennité de la collecte au fil du temps incertaine.

. . .

- Les risques légaux sont existants, et plus généralement cela peut nuire à l'image d'un INS. 
    + Il vaut mieux favoriser des relations de confiance avec les sites concernés.

. . .

::: {.callout-tip}
## Remarque

Il est préférable de privilégier d'autres modes d'accès aux données lorsque cela est possible.
:::


## Dans ces conditions, quand envisager le web scraping ? {.smaller}

<br>

La politique de l'INSEE est de garder le web scraping comme __dernière option__. Les premières étapes recommandées sont d'abord de :

- Demander directement aux sites concernés l'accès à leurs données et nouer d'éventuels partenariats, par exemple modulo une contrepartie

. . .

- Chercher s'il existe une [API](https://fr.wikipedia.org/wiki/Interface_de_programmation) du site permettant d'accéder aux données (ou la demander)

. . .

- Chercher des alternatives, comme accéder à des données similaires via un moyen moins contraignant


## Pour un scraping éthique (et légal !)

- Le web scraping reste malgré tout une nouvelle source de données très pratique dans le cas où aucune meilleure alternative ne se présente.
    + Il ne faut donc pas s'en priver lorsque c'est techniquement et juridiquement propice.

. . .

- Cependant, il existe des moyens de scraper de façon honnête, "éthique" et en minimisant la charge sur le site scrapé.
    + Cela passe par exemple par __demander la permission__ aux sites à scraper, ce qui peut aussi conduire à un éventuel partenariat.


## Les guidelines du `Système Statistique Européen` {.smaller}

<br>

- Un [ensemble de recommandations](https://ec.europa.eu/eurostat/cros/content/web-content-retrieval-guidelines-0_en) principalement à destination des INS publié durant l'été 2022

. . .

- La [version précédente](https://ec.europa.eu/eurostat/cros/system/files/04_-_web_scraping_policy.doc) datant de février 2020 également disponible

. . .

> In the context of the work on Big Data and Trusted Smart Statistics, the European Statistical System (ESS) increasingly utilises information published on the World Wide Web. To ensure that web scraping activities of European Statistical System (ESS) members, namely Eurostat and the national statistical institutes (NSIs) are carried out transparently, and in line with ethical and legal provision, this document proposes guidelines for an ESS wide web scraping policy. Once adopted, these guidelines not only foster nationally sound practices but also ensure a consistent approach across the ESS.


## Les guidelines du `Système Statistique Européen`

#### Transparence

- Rendre publique la liste des collectes de données par scraping de l'INS, autrement dit être [__transparent__]{.blue2}

. . .

- Si l'impact sur site va être important (par exemple un scraping fait très fréquemment), [__informer spécifiquement le site concerné__]{.blue2}
    + Plus généralement, prendre le réflexe de demander la permission

. . .

- [__S'identifier__]{.blue2} auprès du site lors de l'opération de scraping


## Les guidelines du `Système Statistique Européen`

#### Minimiser l'impact

- Toujours chercher à [__minimiser l'impact__]{.blue2} sur les serveurs du site scrapé
    + Notamment en [__limitant les requêtes__]{.blue2} effectuées au minimum requis

. . .

- Privilégier les [__heures creuses__]{.blue2} du site pour les opérations automatisées de scraping

. . .

- [__Étaler les requêtes__]{.blue2} en laissant un temps de 'pause' entre chaque requête, surtout sur un même domaine


## Les guidelines du `Système Statistique Européen`

#### Confiance

- [__Favoriser les échanges__]{.blue2} avec les propriétaires des sites : partenariats, échanges de données, requêtes d'API...

. . .

- [__Se plier aux conditions d'utilisation__]{.blue2} des sites concernés et aux réglementations de la zone concernée

. . .

- Manipuler de façon sécurisée les données scrapées, notamment les données personnelles
    + Ex : [__Respecter le RGPD__]{.blue2}, d'application extraterritoriale


## ⚠️ Ce qu'il ne faut pas faire ! {.smaller}

<br>

- Consciemment déroger aux réglementations applicables et manquer de transparence

. . .

- Surcharger les requêtes sur le site concerné (assimilable à une attaque `DoS`) ou multiplier les mêmes requêtes plusieurs fois

. . .

- Scraper un site entier lorsque l'on a seulement besoin d'une portion de son contenu

. . .

- Paralléliser les requêtes sur un site ou faire ces dernières en heures pleines

. . .

- Diffuser de façon non autorisée des données scrapées non publiques ou soumises à droit d'auteur

. . .

- Pour un INS, utiliser le scraping à des fins non statistiques ou hors du champ légal


## Avertissements {.smaller}

- Selon les pays, il existe des données qui sont publiques mais dont le scraping est illégal.
    + Il faut donc bien se renseigner sur les lois locales.
    + Par exemple, la collecte d'adresses mail par scraping est illégale en Australie, en raison du [Spam Act](https://en.wikipedia.org/wiki/Spam_Act_2003) de 2003.

. . .

- Dans le doute, ne pas hésiter à se documenter davantage.
    - Exemples de ressources : [Carpentries](https://librarycarpentry.org/lc-webscraping/05-conclusion/index.html), [Rubyroidlabs](https://rubyroidlabs.com/blog/2016/04/web-scraping-1/)...

. . .

- Il existe parfois des structures dont le rôle est justement d'évaluer l'aspect juridique de pratiques comme le web scraping.
    + A l'INSEE, c'est la responsabilité de l'[UAJC](https://lannuaire.service-public.fr/gouvernement/bd0be1df-7153-44b0-ab29-43d125837532)

. . .

- Outre l'aspect juridique, il faut bien passer en revue les impacts méthodologiques liés aux risques techniques du web scraping (collecte incomplète, rupture de collecte).
