## Les investissements d'Eurostat en webscraping

- Eurostat investit dans divers projets nommés [ESSnets](https://ec.europa.eu/eurostat/cros/page/essnet_en).
    + "An ESSnet project is a network of several `ESS` organisations aimed at providing results that will be beneficial to the whole `ESS`."

. . .

- Parmi ces investissements, plusieurs liés aux nouvelles sources de données, dont le webscraping.
    + ESSnet Big Data I & II
    + Trusted Smart Statistics – Web Intelligence Network (`WIN`)


## Une continuité de projets

3 ESSnets dans la continuité les uns des autres :

. . .

- [Big Data I](https://ec.europa.eu/eurostat/cros/essnet-big-data-1_en) de février 2016 à mai 2018

. . .

- [Big Data II](https://ec.europa.eu/eurostat/cros/essnet-big-data-2_en) de novembre 2018 à juin 2021

. . .

- Le [Web Intelligence Network](https://ec.europa.eu/eurostat/cros/content/project-overview_en) (`WIN`) d'avril 2020 à mars 2025
    + Le `WIN` fait notamment la promotion du Web Intelligence Hub (`WIH`), dédié au thème de l'acquisition et l'utilisation de nouvelles données venant du Web.
    + Ce sont 17 organisations de 14 pays européens qui travaillent ensemble.


## Un découpage en work packages

Ces ESSnets couvrent une variété de projets. Ceux-ci sont organisés par work packages, chacun avec ses propres objectifs.

. . .

- Pour le WIN, on compte 4 work packages :
    + [WP 1](https://ec.europa.eu/eurostat/cros/content/work-package-1-%E2%80%93-coordination-support-and-dissemination_en) : Coordination, support et dissémination
    + [WP 2](https://ec.europa.eu/eurostat/cros/content/work-package-2-%E2%80%93-oja-and-obec-software_en) : Les projets `OJA` et `OBEC`
    + [WP 3](https://ec.europa.eu/eurostat/cros/content/work-package-3-%E2%80%93-new-use-cases_en) : Nouveaux cas d'usage
    + [WP 4](https://ec.europa.eu/eurostat/cros/content/work-package-4-%E2%80%93-methodology-and-quality_en) : Méthodologie et qualité

. . .

- L'INSEE est engagé dans les work packages 3 et 4.
