## Scraping à l'INSEE

#### Quand ? 

<br>

- Le web scraping est utilisé en __dernier recours__, l'INSEE favorisera :
    + Les [__accords__]{.blue2} avec des partenaires (ex : seloger.com)
    + L'utilisation d'[__API__]{.blue2} (ex : Qwant, Yahoo Finance)
    + Les sources de [__données publiques__]{.blue2}

. . .

- Le web scraping devient cependant une source de données grandissante.


## Scraping à l'INSEE

#### Utilisation

Le scraping est notamment utilisé pour le calcul des [__indices des prix__]{.blue2} :

. . .

- Prix des __transports__ (trains via site de la `SNCF`, domaine maritime) ;

. . .

- Prix de __produits divers__ (surtout de l'électronique) ;

. . .

- Prix dans le domaine de l'__hôtellerie__ (avec `booking.com`).

. . .

D'autres utilisations ponctuelles peuvent également être faites.


## Scraping à l'INSEE

#### Organisation


<br>

- Un scraping encore par cas d'usage, avec une gestion plus globale en cours de maturité
    + Objectif de mutualisation entre les équipes statistiques
    + La logique open source comme moyen de mutualisation

. . .

- Beaucoup de `Python`, un peu de `R` et de `Java`
